library/urls.py
from django.urls import path

from library import views

app_name = 'library'

urlpatterns = [
    path(
        'lista-libri/',
        views.BookListView.as_view(),
        name="book_list"
    )
]

library_api_v1/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter

from library_api_v1 import api_views

app_name = 'library_api_v1'

book_router = SimpleRouter()

book_router.register(
    'libri',
    api_views.BookViewSet,
    basename="books"
)

urlpatterns = book_router.urls

# urlpatterns = [
#     path(
#         'libri/',
#         api_views.BookListAPIView.as_view(),
#         name="book_list"
#     )
# ]

library_project/urls.py
from django.contrib import admin
from django.urls import path, include

from library_project.views import home, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        'biblioteca/',
        include('library.urls')
    ),
    path(
        'api/v1/',
        include('library_api_v1.urls')
    ),
    path('logout/', logout_view, name='logout'),
    path('', home, name='home'),
]

library/models.py
from django.db import models
from django.utils.text import slugify


def image_path(instance, filename):
    return "images/uploaded/" \
           "{id:05d}-{file_name}.{file_extension}".format(
        id=instance.pk,
        file_name=slugify(instance.name),
        file_extension=filename.split(".")[-1],
    )


class Book(models.Model):
    name = models.CharField(max_length=512)
    description = models.CharField(max_length=1024)
    cover_image = models.ImageField(
        upload_to=image_path
    )

    def save(self, *args, **kwargs):
        if self.pk is None:
            self.description = f"Descrizione di {self.name}"
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Libro: {self.name}"

library/views.py
from django.views.generic import ListView

from library.models import Book

__all__ = ['BookListView']


class BookListView(ListView):
    model = Book

library_project/views.py
from django.contrib.auth import logout
from django.http import HttpResponse
from django.shortcuts import render, redirect

__all__ = ['home']


def home(request):
    return render(request, "home.html", {})


def logout_view(request):
    logout(request)
    return redirect('home')

library/templates/library/book_list.html
{% extends 'structure/list.html' %}

templates/home.html
{% extends 'structure/base.html' %}

{% block content %}
    <h1>Welcome!</h1>
{% endblock %}

templates/structure/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <nav class="container my-3">
        <a href="{% url 'home' %}">Home</a>
        <a href="{% url 'library:book_list' %}">Libri</a>
        {% if user.is_authenticated %}
            <span>Benvenuto/a {{ user.username }}</span>
        {% endif %}
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

templates/structure/list.html
{% extends 'structure/base.html' %}

{% block content %}
    {% if object_list %}
        <p>Lista degli oggetti:</p>
        <ul>
            {% for obj in object_list %}
                <li>{{ obj }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Nessun oggetto trovato!</p>
    {% endif %}
{% endblock %}